        <div class="content">

            <div class="content50">

                <div class="logo">
                    <img src="<?= $this->basePath('img/iconos-home.png') ?>" />
                </div>
                
                <h1>
                    Inventario Nacional de Gases de<br/>
                    Efecto Invernadero (GEI) de Argentina
                </h1>

                <div class="guion">
                    <img src="<?= $this->basePath('img/home-guion.png') ?>" />
                </div>

                <h2>El Inventario Nacional de GEI contabiliza los gases emitidos y absorbidos
                de la atmósfera durante un año calendario para el territorio argentino.</h2>


                <p>Incluye sólo aquellas fuentes de emisión y absorción para las cuales se contó
                con la información disponible para realizar la estimación, según los principios de calidad del <strong>Panel Intergubernamental de Expertos en Cambio Climático (IPCC)</strong>.</p>

                <div class="buttons">
                    <a href="<?= $this->basePath('files/inventario-nacional-gei-argentina.pdf') ?>" target="_blank"><button>VER INFORME</button></a>
                    <a href="resultados"><button >VER RESULTADOS</button></a>
                </div>

            </div>

        </div>